### PR TITLE
Keep classes clean, obey WPCS and remove executable bits

### PR DESCRIPTION
**Pull request by szepeviktor**
Moved the main `Minit_Pro` class to `/inc`. This way all files are one-class-only.

### CODE REVIEW

**Comment by szepeviktor** [comment]
I am not sure of the name `inc/minitpro.php`

**Comment by markoheijnen** [comment]
I'm not really eager to merge this one. I do generally obey WPCS except the if/else statement.

Also moving Minit_Pro to it's own file doesn't add any value. You also made a typo including that file.

**Comment by szepeviktor** [comment]
> Also moving Minit_Pro to it's own file doesn't add any value.

OK. The value would be _clean classes_.

**Comment by szepeviktor** [comment]
But of course you may close this one.

**Comment by szepeviktor** [comment]
How about reverting moving Minit_Pro to it's own file, and merging the rest?

**Pull request closed without merging**
